// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-layout/internal/conf"
	"go-layout/internal/dao"
	"go-layout/internal/server/http"
	"go-layout/internal/server/http/handler"
	"go-layout/internal/server/http/middleware"
	"go-layout/internal/server/http/router"
	"go-layout/internal/service"
	"go-layout/pkg/app"
)

// Injectors from wire.go:

func wireApp(c *conf.Conf) *app.App {
	daoDao := dao.New(c)
	serviceService := &service.Service{
		Dao:  daoDao,
		Conf: c,
	}
	handlerHandler := &handler.Handler{
		Srv: serviceService,
	}
	service2 := service.Service{
		Dao:  daoDao,
		Conf: c,
	}
	middlewareMiddleware := &middleware.Middleware{
		Srv: service2,
	}
	routerRouter := &router.Router{
		Handler:    handlerHandler,
		Middleware: middlewareMiddleware,
	}
	server := http.NewServer(routerRouter, c)
	appApp := &app.App{
		HTTPServer: server,
		Svc:        serviceService,
	}
	return appApp
}
